### ISSUE TITLE
pytorch_lightning.py is missing Activity1.2 feature 

### ISSUE THREAD

**Issue by BCIer** [asrafulashiq/hamnet#1]
First, thank you for your excellent work!
I cloned your hamnet code and found that the pytorch_lightning.py was missing.
Could you share this file?

And would you share the I3D feature about THUMOS14 and ActivityNet1.2, especially ActivityNet1.2?

Thanks a lot!

**Comment by asrafulashiq** [comment]
Please install [pytorch-lightning](https://pytorch-lightning.readthedocs.io/en/stable/) first: either using `pip install pytorch_lightning`, or install all dependencies in a conda environemnt by `conda env create -f environment.yml`.

The features can be downloaded from this link: [Box link](https://rpi.box.com/s/hf6djlgs7vnl7a2oamjt0vkrig42pwho).

Thanks for your interest in the paper.

**Comment by BCIer** [comment]
> Please install [pytorch-lightning](https://pytorch-lightning.readthedocs.io/en/stable/) first: either using `pip install pytorch_lightning`, or install all dependencies in a conda environemnt by `conda env create -f environment.yml`.
> 
> The features can be downloaded from this link: [Box link](https://rpi.box.com/s/hf6djlgs7vnl7a2oamjt0vkrig42pwho).
> 
> Thanks for your interest in the paper.

Thank you for your reply!
