### ISSUE TITLE
About ablation study

### ISSUE THREAD

**Issue by topdou96** [asrafulashiq/hamnet#3]
When I only remain BCL Loss and SAL Loss，my AVG mAP can only reach 0.38%，I don't know the reason. 
Which part of the code do I need to adjust?
![image](https://user-images.githubusercontent.com/40995351/117597274-d0f6ec80-b177-11eb-8217-f3940dd877e9.png)
![image](https://user-images.githubusercontent.com/40995351/117597250-c5a3c100-b177-11eb-974c-ac5e5fbc5e9f.png)

**Comment by asrafulashiq** [comment]
Hi, the ablations were performed with separate hyper-parameter tuning on each experiment, and the best scores are reported in the table. Hence, the original hyper-parameters might not work for the current ablation.

**Comment by asrafulashiq** [comment]
Another thing is, when we are not optimizing the attention loss, we should not use foreground attention scores to get action proposal (`system/tester.py:85`). When you only optimize BCL and SAL loss, please modify `system/tester.py` file by
- adding the following command after line 91:
```python
                cas_norm = (cas_temp - cas_temp.min(axis=0, keepdims=True)) / (
                    cas_temp.max(axis=0, keepdims=True) -
                    cas_temp.min(axis=0, keepdims=True) + 1e-4)
```

- replace line 96 (`pos = np.where(cas_temp_atn[:, 0, 0] > act_thresh[i])`) by:
```
pos = np.where(cas_norm[:, c, 0] > act_thresh[i])
```

Hope it helps.

**Comment by topdou96** [comment]
> Another thing is, when we are not optimizing the attention loss, we should not use foreground attention scores to get action proposal (`system/tester.py:85`). When you only optimize BCL and SAL loss, please modify `system/tester.py` file by
> 
> * adding the following command after line 91:
> 
> ```python
>                 cas_norm = (cas_temp - cas_temp.min(axis=0, keepdims=True)) / (
>                     cas_temp.max(axis=0, keepdims=True) -
>                     cas_temp.min(axis=0, keepdims=True) + 1e-4)
> ```
> 
> * replace line 96 (`pos = np.where(cas_temp_atn[:, 0, 0] > act_thresh[i])`) by:
> 
> ```
> pos = np.where(cas_norm[:, c, 0] > act_thresh[i])
> ```
> 
> Hope it helps.

Thanks, it succeeded
